services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./config:/app
      - ./downloads:/downloads
    restart: unless-stopped
